require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'config/routes/**/*'
    - 'config/locales/**/*'
    - 'config/initializers/**/*'
    - 'config/application.rb'
    - 'config/puma.rb'

Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Security/Eval:
  Enabled: true

Style/GlobalStdStream:
  Enabled: false

Style/Documentation:
  Enabled: false